name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/html
    steps:
      - uses: actions/checkout@v2
